- name: Recreate local mysql database
  delegate_to: localhost
  become: false
  shell: >
    {{ db_pull_mysql_mysql_binary_path }} \
      -u {{ db_pull_local_database_user }} \
      --password={{ db_pull_local_database_password }} \
      -h {{ db_pull_local_database_host }} \
      -e "CREATE DATABASE IF NOT EXISTS \`{{ db_pull_local_database_name }}\` CHARACTER SET utf8 COLLATE utf8_general_ci;"
