- name: Remove local mysql database
  delegate_to: localhost
  become: false
  shell: >
    {{ db_pull_mysql_mysql_binary_path }} \
      -u {{ db_pull_local_database_user }} \
      --password={{ db_pull_local_database_password }} \
      -h {{ db_pull_local_database_host }} \
      -e "DROP DATABASE IF EXISTS \`{{ db_pull_local_database_name }}\`;"
  when: not db_pull_skip_restore
