- name: Recreate local postgres database
  delegate_to: localhost
  become: false
  shell: >
    PGPASSWORD="{{ db_pull_local_database_password }}" {{ db_pull_postgresql_createdb_binary_path }} \
      -U {{ db_pull_local_database_user }} \
      -h {{ db_pull_local_database_host }} \
      {{ db_pull_local_database_name }}
