- name: Remove local postgres database
  delegate_to: localhost
  become: false
  shell: >
    PGPASSWORD="{{ db_pull_local_database_password }}" {{ db_pull_postgresql_dropdb_binary_path }} --if-exists \
      -U {{ db_pull_local_database_user }} \
      -h {{ db_pull_local_database_host }} \
      {{ db_pull_local_database_name }}
  when: not db_pull_skip_restore
